-- ═══════════════════════════════════════════════════════════
-- Table: player_summaries
-- Periodic summaries for the "return after absence" flow.
-- Generated by server every hour per player with active species.
-- ═══════════════════════════════════════════════════════════

CREATE TABLE player_summaries (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  world_id      UUID NOT NULL REFERENCES worlds(id) ON DELETE CASCADE,
  player_id     UUID NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  summary       JSONB NOT NULL,
  period_start  TIMESTAMPTZ NOT NULL,
  period_end    TIMESTAMPTZ NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_summaries_player_date ON player_summaries (player_id, period_end DESC);
